# Generated by Django 5.1.4 on 2025-02-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_contactusform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusform',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
